name: DevOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show system
        run: |
          uname -a
          pwd
          ls -la

      - name: Test
        run: echo "Tests passed"

  build:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build completed"
